---
models:
  - type: main
    engine: ollama
    model: llama3.1:8b
    parameters:
      base_url: http://localhost:11434

  - type: chat_conversation_check
    engine: ollama
    model: llama3.1:8b
    parameters:
      base_url: http://localhost:11435
      raw: True

rails:
  input:
    flows:
      - chat conversation check

actions:
  module: actions
